<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKgX5qku\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKgX5qku/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKgX5qku.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKgX5qku\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKgX5qku\App_KernelDevDebugContainer([
    'container.build_hash' => 'KgX5qku',
    'container.build_id' => '394dbd24',
    'container.build_time' => 1701290261,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKgX5qku');
